version: "3.9"

services:
  n8n:
    # image: n8nio/n8n:latest
    build: .
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - N8N_LOG_LEVEL=debug
      - N8N_RUNNERS_ENABLED=true
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem # or 'database'

    volumes:  
      - ./n8n_data:/home/node/.n8n
      - /Users/2noscript/workspace/project/n8n-nodes-multitasking:/home/node/.n8n/custom/n8n-nodes-multitasking
      - /Users/2noscript/workspace/project/n8n-nodes-video-mzz:/home/node/.n8n/custom/n8n-nodes-video-mzz
